I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game_keysym.rpy", line 6, in script
    $ config.keymap['game_menu'].remove('mousedown_3')
  File "game/game_keysym.rpy", line 6, in script
    $ config.keymap['game_menu'].remove('mousedown_3')
  File "game/game_keysym.rpy", line 6, in <module>
    $ config.keymap['game_menu'].remove('mousedown_3')
ValueError: list.remove(x): x not in list

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/game_keysym.rpy", line 6, in script
    $ config.keymap['game_menu'].remove('mousedown_3')
  File "game/game_keysym.rpy", line 6, in script
    $ config.keymap['game_menu'].remove('mousedown_3')
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/game_keysym.rpy", line 6, in <module>
    $ config.keymap['game_menu'].remove('mousedown_3')
  File "renpy/python.py", line 875, in do_mutation
    return method(self, *args, **kwargs)
ValueError: list.remove(x): x not in list

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
CGJ2021 1.8
Sun Jul 11 14:14:47 2021
